### PR TITLE
Added the possibility to run multipe actions & added tests

### PR DESCRIPTION
**Pull request by sekel**
As of this change you can specify multiple events and actions for a repo
by defining a actions hash in tutter.yaml. Like so:
```
projects:
  - name: 'JHaals/testing'
    access_token: ''
    github_site: 'https://github.com'
    github_api_endpoint: 'https://api.github.com'

    actions:
      issue:
        - thanks
        - sassy
      issue_comment:
        - sassy

    action_settings:
        whatever_action_specific_setting: 'foo'
        another_setting: false
```

Tutter will look for the specifed actions and run them in the sequence
specified. If an action where to return anything other than `200 OK` the chain
will stop at the action that broke the chain and only return a response for
that action. With the config above and a hook for an isse the response would
be some thing like:

```
{
  "event":"issue",
  "responses":{
                "thanks":{
                          "status_code":401,
                          "message":"Authorization to JHaals/testing failed, please verify your access token"
                         }
              }
}
```
Some test where also added to check the most common error codes.

**This pull request will introduce breaking changes when it comes to how config.yml must look like.**

### CODE REVIEW

**Comment by jhaals** [comment]
Great update @sekel!
I'll try to review this as soon as I get some time. 

The sequence stuff is really interesting. It's something I discussed recently with @dalen. 
We talked about being about having dependency chains like pam. 

Example: 

```yaml
actions:
  issue:
    - name: Verify gamma protection
      action: gamma_protector
      dependency: required
      settings:
        radiator: 300
    - name: flux capacitor
      action: flux_capacitor
      dependency: sufficient
```

But this might be great initially :+1:

**Comment by sekel** [comment]
Thanks @jhaals,

Ok, Cool! Lets see what the review brings and if this is a ok approach i'll implement that on top of this change. :)

**Comment by jhaals** [comment]
@sekel code looks good! :+1: 

Yes that's the PAM policies, that would bring us to a 1.0.0 :smiley:

**Comment by sekel** [comment]
@jhaals Cool, I'll work in this during the holidays and get back to you with some updates with the PAM chain support.

**Comment by jhaals** [comment]
awesome!

**Pull request merged**
